export const GET_LOCATIONS = "GET_LOCATIONS";
export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";
export const SET_SEARCH_LOCATION = "SET_SEARCH_LOCATION"
export const CREATE_LOCATION = "CREATE_LOCATION";
export const LOADING = "LOADING";


export const CURRENT_USER = "CURRENT_USER";

